baseurl: /riverside
permalink: pretty
markdown: kramdown
paginate: 5
repo: riverside
github_org: maptime
future: true
maptime:
  chapter: MaptimeIE
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
